import {
  defaultSettings,
  type MurmurationSettings,
} from "./settings";

export type PresetName =
  | "Quiet Roost"
  | "Comfort Flight"
  | "Swarm Pilot"
  | "Acro Swarm"
  | "Quest 2 Dense"
  | "Lava Lamp"
  | "Ink Cloud"
  | "Predator Ripple"
  | "Vacuole"
  | "Silk Sheet"
  | "Storm Turn";

export type Preset = Readonly<{
  name: PresetName;
  settings: MurmurationSettings;
}>;

const preset = (
  name: PresetName,
  overrides: Partial<MurmurationSettings>,
): Preset => ({
  name,
  settings: {
    ...defaultSettings,
    ...overrides,
  },
});

export const presets = [
  preset("Quiet Roost", {
    count: 3000,
    speed: 0.48,
    minSpeed: 0.06,
    maxSpeed: 1.2,
    separation: 0.85,
    alignment: 0.65,
    cohesion: 1.85,
    inertia: 0.82,
    noise: 0.03,
    flow: 0.18,
    chaseStrength: 0.72,
    attractorRadius: 0.5,
    attractorSpeed: 0.55,
    trailMode: "velocity",
    trailLength: 0.24,
    trailOpacity: 0.12,
    fov: 52,
  }),
  preset("Comfort Flight", {
    count: 4200,
    speed: 0.36,
    minSpeed: 0.04,
    maxSpeed: 0.9,
    separation: 0.8,
    alignment: 0.58,
    cohesion: 1.9,
    inertia: 0.9,
    noise: 0.018,
    flow: 0.16,
    chaseStrength: 0.78,
    attractorRadius: 0.38,
    attractorSpeed: 0.42,
    particleScale: 0.76,
    particleOpacity: 0.92,
    mediumMode: "air",
    mediumIntensity: 0.72,
    mediumTurbulence: 0.2,
    mediumWake: 0.36,
    mediumPointScale: 0.74,
    trailMode: "off",
    targetFps: 72,
    pixelRatioCap: 1,
    fov: 48,
  }),
  preset("Swarm Pilot", {
    count: 6400,
    speed: 0.54,
    minSpeed: 0.05,
    maxSpeed: 1.25,
    separation: 0.9,
    alignment: 0.78,
    cohesion: 1.7,
    inertia: 0.82,
    noise: 0.035,
    flow: 0.28,
    chaseStrength: 0.82,
    attractorRadius: 0.72,
    attractorSpeed: 0.74,
    particleScale: 0.72,
    mediumMode: "dust",
    mediumIntensity: 0.78,
    mediumTurbulence: 0.32,
    mediumWake: 0.56,
    mediumPointScale: 0.82,
    trailMode: "off",
    targetFps: 72,
    pixelRatioCap: 1,
  }),
  preset("Acro Swarm", {
    count: 5200,
    speed: 0.82,
    minSpeed: 0.06,
    maxSpeed: 1.85,
    separation: 1.02,
    alignment: 1.05,
    cohesion: 1.42,
    inertia: 0.62,
    noise: 0.08,
    flow: 0.62,
    chaseStrength: 0.58,
    attractorRadius: 0.95,
    attractorSpeed: 1.36,
    particleScale: 0.68,
    mediumMode: "starlight",
    mediumIntensity: 0.84,
    mediumTurbulence: 0.18,
    mediumWake: 0.7,
    mediumPointScale: 0.72,
    trailMode: "off",
    targetFps: 72,
    pixelRatioCap: 1,
    fov: 56,
  }),
  preset("Quest 2 Dense", {
    count: 8000,
    speed: 0.48,
    minSpeed: 0.04,
    maxSpeed: 1.08,
    separation: 0.86,
    alignment: 0.7,
    cohesion: 1.82,
    inertia: 0.86,
    noise: 0.024,
    flow: 0.22,
    chaseStrength: 0.84,
    attractorRadius: 0.62,
    attractorSpeed: 0.64,
    particleScale: 0.6,
    particleOpacity: 0.86,
    depthScale: 0.88,
    mediumMode: "grid",
    mediumIntensity: 0.62,
    mediumTurbulence: 0.16,
    mediumWake: 0.42,
    mediumPointScale: 0.64,
    trailMode: "off",
    targetFps: 72,
    pixelRatioCap: 1,
  }),
  preset("Lava Lamp", {
    count: 16000,
  }),
  preset("Ink Cloud", {
    count: 18000,
    speed: 0.62,
    separation: 0.92,
    alignment: 0.9,
    cohesion: 1.8,
    noise: 0.035,
    flow: 0.3,
    chaseStrength: 0.82,
    attractorRadius: 1.34,
    attractorSpeed: 1.08,
    particleScale: 0.82,
    depthFade: 0.55,
    trailLength: 0.16,
    trailOpacity: 0.1,
  }),
  preset("Predator Ripple", {
    count: 12000,
    speed: 0.78,
    maxSpeed: 1.8,
    separation: 1.05,
    alignment: 1.05,
    cohesion: 1.15,
    inertia: 0.7,
    noise: 0.08,
    flow: 0.48,
    chaseStrength: 0.64,
    attractorRadius: 1.08,
    attractorSpeed: 1.18,
    threatMode: "orbit",
    threatStrength: 0.72,
    threatRadius: 0.24,
    waveGain: 1.35,
    blackeningGain: 0.58,
    trailLength: 0.48,
  }),
  preset("Vacuole", {
    count: 10000,
    speed: 0.68,
    maxSpeed: 1.6,
    separation: 1.12,
    alignment: 0.92,
    cohesion: 1.25,
    flow: 0.42,
    chaseStrength: 0.76,
    attractorRadius: 0.96,
    attractorSpeed: 1.02,
    threatMode: "autonomous",
    threatStrength: 0.68,
    threatRadius: 0.32,
    vacuoleStrength: 1.45,
    splitGain: 0.34,
  }),
  preset("Silk Sheet", {
    count: 14000,
    speed: 0.46,
    minSpeed: 0.05,
    maxSpeed: 1.1,
    neighborRadius: 0.16,
    separation: 0.92,
    alignment: 1.1,
    cohesion: 1.1,
    inertia: 0.88,
    noise: 0.025,
    flow: 0.24,
    chaseStrength: 0.68,
    attractorRadius: 1.12,
    attractorSpeed: 0.68,
    particleScale: 0.74,
    trailLength: 0.42,
  }),
  preset("Storm Turn", {
    count: 16000,
    speed: 0.9,
    maxSpeed: 2.1,
    separation: 1.1,
    alignment: 1.15,
    cohesion: 1.25,
    inertia: 0.58,
    noise: 0.1,
    flow: 0.72,
    chaseStrength: 0.42,
    attractorRadius: 1.28,
    attractorSpeed: 1.55,
    threatMode: "autonomous",
    threatStrength: 0.46,
    threatRadius: 0.2,
    waveGain: 1.7,
    trailLength: 0.62,
  }),
] as const satisfies readonly Preset[];

export const presetNames = presets.map(({ name }) => name);

export const presetByName = (name: PresetName): Preset =>
  presets.find((candidate) => candidate.name === name) ?? presets[0];
